# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml  # Use MkDocs with this config

python:
  install:
    - requirements: requirements.txt  # Install mkdocs from pip
