site_name: MkDocs test
docs_dir: docs
use_directory_urls: false

theme:
  name: readthedocs

nav:
  - Table of Contents: index.md
  - Chapter 1: chapter1/chapter1.md
  - Chapter 2: chapter2/chapter2.md